### ISSUE TITLE
ios error

### ISSUE THREAD

**Issue by pheromone** [yy1300326388/app_installer#1]
安装后:
Xcode:
The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
pod install 后:
[!] Unable to determine Swift version for the following pods:
install_plugin does not specify a Swift version and none of the targets (Runner) integrating it have the SWIFT_VERSION attribute set. Please contact the author or set the SWIFT_VERSION attribute in at least one of the targets that integrate this pod.
![image](https://user-images.githubusercontent.com/14305431/66883366-492f1780-f000-11e9-8592-f1c8fd2dd368.png)

**Comment by yy1300326388** [comment]
@pheromone  我稍后升级

**Comment by yy1300326388** [comment]
我这边插件是 OC 写的，你的主项目是 Swift 的吗？可以参考这个设置一下
[https://github.com/ko2ic/image_downloader/issues/9#issuecomment-471608482](https://github.com/ko2ic/image_downloader/issues/9#issuecomment-471608482)
