### ISSUE TITLE
安装包下载到自定义的目录下无法触发安装

### ISSUE THREAD

**Issue by StitchC** [yy1300326388/app_installer#11]
你好我使用的插件进行apk 安装
我的apk 下载目录是 /data/user/0/${packageName}/app_flutter/update/erp_app_47895935d5b93b4f0728188f2d713ee80473d16c8c53a950839ab2301ce6c7f8.apk

然后调用 installApk api 后报了这样的错
<img width="1668" alt="image" src="https://user-images.githubusercontent.com/21286819/215686462-e04032d1-f053-425a-bee2-65eab860c351.png">

看错误内容应该是要把安装包下载到 /data/data/${packageName}/ 这个目录下面才能触发安装吗？

**Comment by StitchC** [comment]
这个问题已解决 我将安装包下载到 app 内部存储的目录里面就可以了，但是我发现在安卓4.x 的系统上，只要触发安装就会提示“无法解析安装包” 的错误，是什么原因呢？

**Comment by yy1300326388** [comment]
没有遇到过这个问题

**Comment by yy1300326388** [comment]
这个应该是和你的 FileProvider 相关，https://github.com/yy1300326388/app_installer/blob/master/example/android/app/src/main/res/xml/file_paths.xml

**Comment by StitchC** [comment]
> 这个应该是和你的 FileProvider 相关，https://github.com/yy1300326388/app_installer/blob/master/example/android/app/src/main/res/xml/file_paths.xml

FileProvider 设置没问题的 其他安卓版本都尝试过可以 但是Android4.x 就一直提示解析程序包出错
