### ISSUE TITLE
{exception: PlatformException(error, Couldn't find meta-data for provider with authority com.example.tsp.fileProvider, null, java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.example.tsp.fileProvider

### ISSUE THREAD

**Issue by li-xiaojun** [yy1300326388/app_installer#12]
{exception: PlatformException(error, Couldn't find meta-data for provider with authority com.example.tsp.fileProvider, null, java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.example.tsp.fileProvider

**Comment by yy1300326388** [comment]
错误很明显，自行解决一下
