### ISSUE TITLE
android 11 申请安装未知应用权限后 重启

### ISSUE THREAD

**Issue by HanGao1** [yy1300326388/app_installer#6]
如题，最新版本，测试发现其他手机没啥问题，但是小米手机依旧弹出一个提示框，需要去设置打开未知应用权限，打开了就还是会重启，望知悉

**Comment by yy1300326388** [comment]
来个截图和小米系统的版本，我排查一下

**Comment by HanGao1** [comment]
![image](https://user-images.githubusercontent.com/19724842/130761315-3d27629b-4d5d-4075-a668-1980a45bc2c9.png)
android 11

**Comment by HanGao1** [comment]
我在小米手机上安装了其他的应用商店，安装时并不会弹出这个，不知道啥原因

**Comment by yy1300326388** [comment]
你这个是禁止了，你卸载 App 然后重新试试，已经禁止的无法调起了

**Comment by HanGao1** [comment]
默认就是禁止的

**Comment by HanGao1** [comment]
我用release版本再试试

**Comment by HanGao1** [comment]
才发现，小米11真机是正常的，但是小米云测平台的手机测试会弹出上面图的提示，也可能是测试机的问题。。。

**Comment by yy1300326388** [comment]
我这边测试也是正常的，感谢你的反馈，后续有问题可继续打开
